import Head from "next/head";
import "../styles/globals.css";
import { ProSidebarProvider } from "react-pro-sidebar";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Olin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-olin.svg" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <ProSidebarProvider>
        <Component {...pageProps} />
      </ProSidebarProvider>
    </>
  );
}

export default MyApp;
